version: '3'

services: 

  react-service:
    build: .
    container_name: react-container
    privileged: true
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:1234